services:
  notesmanager:
    image: ${DOCKER_REGISTRY-}notesmanager
    build:
      context: ./NotesManager
      dockerfile: Dockerfile
    container_name: notesmanager_app
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__WebApiDatabase: Host=db;Port=5432;Database=NotesDb;Username=postgres;Password=1594
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: notesmanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1594
      POSTGRES_DB: NotesDb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: